from talon.voice import Context, Key

context = Context("programming")

context.keymap(
    {
        "args": [ "()", Key("left") ],
        "curly": [ "{}", Key("left") ],
        "brax": [ "[]", Key("left") ],
        "pointy": [ "<>", Key("left") ],
        "string": [ '""', Key("left") ],
        "triple quote": "'''",
        "(dot dot | dotdot)": "..",
        "ellipses": "…",
        "boom": ", ",
        "plus": "+",
        "imply": "->",
        "long imply": " -> ",
        "left imply": " <- ",
        "arrow": "=>",
        "long arrow": " => ",
        "(long | pad) colon": " : ",
        "indirect": "&",
        "dereference": "*",
        "(long equals | assign)": " = ",
        "long (minus | subtract | sub)": " - ",
        "long (plus | add)": " + ",
        "long (times | multiply)": " * ",
        "long divide": " / ",
        "long mod": " % ",
        "[long] (minus | subtract | sub) equals": " -= ",
        "[long] (plus | add) equals": " += ",
        "[long] (times | multiply) equals": " *= ",
        "[long] divide equals": " /= ",
        "[long] mod equals": " %= ",
        "(long | is) greater [than]": " > ",
        "(long | is) less [than]": " < ",
        "is equal": " == ",
        "long dot": " . ",
        "(long | is) not equal": " != ",
        "(long | is) greater [than] or equal": " >= ",
        "(long | is) less [than] or equal": " <= ",
        "(long (power | exponent) | to the power [of])": " ** ",
        "(long | logical) and": " && ",
        "long or": " || ",
        "[long] (logical | bitwise) and": " & ",
        "[long] bitwise or": " | ",
        "[long] logical or": " || ",
        "(long | logical | bitwise) (ex | exclusive) or": " ^ ",
        "[(long | logical | bitwise)] (left shift | shift left)": " << ",
        "[(long | logical | bitwise)] (right shift | shift right)": " >> ",
        "(long | logical | bitwise) and equals": " &= ",
        "(long | logical | bitwise) or equals": " |= ",
        "(long | logical | bitwise) (ex | exclusive) or equals": " ^= ",
        "[(long | logical | bitwise)] (left shift | shift left) equals": " <<= ",
        "[(long | logical | bitwise)] (left right | shift right) equals": " >>= ",
    }
)
